# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gaia/liquid/v1beta1/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from gaia.liquid.v1beta1 import liquid_pb2 as gaia_dot_liquid_dot_v1beta1_dot_liquid__pb2
from amino import amino_pb2 as amino_dot_amino__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!gaia/liquid/v1beta1/genesis.proto\x12\x13gaia.liquid.v1beta1\x1a\x14gogoproto/gogo.proto\x1a gaia/liquid/v1beta1/liquid.proto\x1a\x11\x61mino/amino.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x02\n\x0cGenesisState\x12\x36\n\x06params\x18\x01 \x01(\x0b\x32\x1b.gaia.liquid.v1beta1.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01\x12N\n\x16tokenize_share_records\x18\t \x03(\x0b\x32(.gaia.liquid.v1beta1.TokenizeShareRecordB\x04\xc8\xde\x1f\x00\x12%\n\x1dlast_tokenize_share_record_id\x18\n \x01(\x04\x12\x66\n\x1atotal_liquid_staked_tokens\x18\x0b \x01(\x0c\x42\x42\xda\xde\x1f\x15\x63osmossdk.io/math.Int\xf2\xde\x1f!yaml:\"total_liquid_staked_tokens\"\xc8\xde\x1f\x00\x12J\n\x14tokenize_share_locks\x18\x0c \x03(\x0b\x32&.gaia.liquid.v1beta1.TokenizeShareLockB\x04\xc8\xde\x1f\x00\"\x8d\x01\n\x11TokenizeShareLock\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12W\n\x0f\x63ompletion_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\"\xc8\xde\x1f\x00\x90\xdf\x1f\x01\xf2\xde\x1f\x16yaml:\"completion_time\"B\'Z%github.com/cosmos/gaia/x/liquid/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gaia.liquid.v1beta1.genesis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z%github.com/cosmos/gaia/x/liquid/types'
  _GENESISSTATE.fields_by_name['params']._options = None
  _GENESISSTATE.fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _GENESISSTATE.fields_by_name['tokenize_share_records']._options = None
  _GENESISSTATE.fields_by_name['tokenize_share_records']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['total_liquid_staked_tokens']._options = None
  _GENESISSTATE.fields_by_name['total_liquid_staked_tokens']._serialized_options = b'\332\336\037\025cosmossdk.io/math.Int\362\336\037!yaml:\"total_liquid_staked_tokens\"\310\336\037\000'
  _GENESISSTATE.fields_by_name['tokenize_share_locks']._options = None
  _GENESISSTATE.fields_by_name['tokenize_share_locks']._serialized_options = b'\310\336\037\000'
  _TOKENIZESHARELOCK.fields_by_name['completion_time']._options = None
  _TOKENIZESHARELOCK.fields_by_name['completion_time']._serialized_options = b'\310\336\037\000\220\337\037\001\362\336\037\026yaml:\"completion_time\"'
  _GENESISSTATE._serialized_start=167
  _GENESISSTATE._serialized_end=536
  _TOKENIZESHARELOCK._serialized_start=539
  _TOKENIZESHARELOCK._serialized_end=680
# @@protoc_insertion_point(module_scope)
