# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c4echain/cfedistributor/events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from c4echain.cfedistributor import sub_distributor_pb2 as c4echain_dot_cfedistributor_dot_sub__distributor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$c4echain/cfedistributor/events.proto\x12$chain4energy.c4echain.cfedistributor\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a-c4echain/cfedistributor/sub_distributor.proto\"\xb2\x02\n\x0c\x44istribution\x12\x16\n\x0esubdistributor\x18\x01 \x01(\t\x12\x12\n\nshare_name\x18\x02 \x01(\t\x12>\n\x07sources\x18\x03 \x03(\x0b\x32-.chain4energy.c4echain.cfedistributor.Account\x12\x42\n\x0b\x64\x65stination\x18\x04 \x01(\x0b\x32-.chain4energy.c4echain.cfedistributor.Account\x12r\n\x06\x61mount\x18\x05 \x03(\x0b\x32\x1c.cosmos.base.v1beta1.DecCoinBD\xf2\xde\x1f\ryaml:\"amount\"\xaa\xdf\x1f+github.com/cosmos/cosmos-sdk/types.DecCoins\xc8\xde\x1f\x00\"\xde\x01\n\x10\x44istributionBurn\x12\x16\n\x0esubdistributor\x18\x01 \x01(\t\x12>\n\x07sources\x18\x02 \x03(\x0b\x32-.chain4energy.c4echain.cfedistributor.Account\x12r\n\x06\x61mount\x18\x03 \x03(\x0b\x32\x1c.cosmos.base.v1beta1.DecCoinBD\xf2\xde\x1f\ryaml:\"amount\"\xaa\xdf\x1f+github.com/cosmos/cosmos-sdk/types.DecCoins\xc8\xde\x1f\x00\x42:Z8github.com/chain4energy/c4e-chain/x/cfedistributor/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c4echain.cfedistributor.events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8github.com/chain4energy/c4e-chain/x/cfedistributor/types'
  _DISTRIBUTION.fields_by_name['amount']._options = None
  _DISTRIBUTION.fields_by_name['amount']._serialized_options = b'\362\336\037\ryaml:\"amount\"\252\337\037+github.com/cosmos/cosmos-sdk/types.DecCoins\310\336\037\000'
  _DISTRIBUTIONBURN.fields_by_name['amount']._options = None
  _DISTRIBUTIONBURN.fields_by_name['amount']._serialized_options = b'\362\336\037\ryaml:\"amount\"\252\337\037+github.com/cosmos/cosmos-sdk/types.DecCoins\310\336\037\000'
  _DISTRIBUTION._serialized_start=180
  _DISTRIBUTION._serialized_end=486
  _DISTRIBUTIONBURN._serialized_start=489
  _DISTRIBUTIONBURN._serialized_end=711
# @@protoc_insertion_point(module_scope)
