# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c4echain/cfeminter/query.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from c4echain.cfeminter import params_pb2 as c4echain_dot_cfeminter_dot_params__pb2
from c4echain.cfeminter import minter_pb2 as c4echain_dot_cfeminter_dot_minter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63\x34\x65\x63hain/cfeminter/query.proto\x12\x1f\x63hain4energy.c4echain.cfeminter\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x1f\x63\x34\x65\x63hain/cfeminter/params.proto\x1a\x1f\x63\x34\x65\x63hain/cfeminter/minter.proto\"\x14\n\x12QueryParamsRequest\"T\n\x13QueryParamsResponse\x12=\n\x06params\x18\x01 \x01(\x0b\x32\'.chain4energy.c4echain.cfeminter.ParamsB\x04\xc8\xde\x1f\x00\"\x17\n\x15QueryInflationRequest\"[\n\x16QueryInflationResponse\x12\x41\n\tinflation\x18\x01 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\"\x13\n\x11QueryStateRequest\"\xa3\x01\n\x12QueryStateResponse\x12H\n\x0cminter_state\x18\x01 \x01(\x0b\x32,.chain4energy.c4echain.cfeminter.MinterStateB\x04\xc8\xde\x1f\x00\x12\x43\n\rstate_history\x18\x02 \x03(\x0b\x32,.chain4energy.c4echain.cfeminter.MinterState2\xdd\x03\n\x05Query\x12\x97\x01\n\x06Params\x12\x33.chain4energy.c4echain.cfeminter.QueryParamsRequest\x1a\x34.chain4energy.c4echain.cfeminter.QueryParamsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/c4e/minter/v1beta1/params\x12\xa3\x01\n\tInflation\x12\x36.chain4energy.c4echain.cfeminter.QueryInflationRequest\x1a\x37.chain4energy.c4echain.cfeminter.QueryInflationResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/c4e/minter/v1beta1/inflation\x12\x93\x01\n\x05State\x12\x32.chain4energy.c4echain.cfeminter.QueryStateRequest\x1a\x33.chain4energy.c4echain.cfeminter.QueryStateResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/c4e/minter/v1beta1/stateB5Z3github.com/chain4energy/c4e-chain/x/cfeminter/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c4echain.cfeminter.query_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/chain4energy/c4e-chain/x/cfeminter/types'
  _QUERYPARAMSRESPONSE.fields_by_name['params']._options = None
  _QUERYPARAMSRESPONSE.fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _QUERYINFLATIONRESPONSE.fields_by_name['inflation']._options = None
  _QUERYINFLATIONRESPONSE.fields_by_name['inflation']._serialized_options = b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000'
  _QUERYSTATERESPONSE.fields_by_name['minter_state']._options = None
  _QUERYSTATERESPONSE.fields_by_name['minter_state']._serialized_options = b'\310\336\037\000'
  _QUERY.methods_by_name['Params']._options = None
  _QUERY.methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\034\022\032/c4e/minter/v1beta1/params'
  _QUERY.methods_by_name['Inflation']._options = None
  _QUERY.methods_by_name['Inflation']._serialized_options = b'\202\323\344\223\002\037\022\035/c4e/minter/v1beta1/inflation'
  _QUERY.methods_by_name['State']._options = None
  _QUERY.methods_by_name['State']._serialized_options = b'\202\323\344\223\002\033\022\031/c4e/minter/v1beta1/state'
  _QUERYPARAMSREQUEST._serialized_start=229
  _QUERYPARAMSREQUEST._serialized_end=249
  _QUERYPARAMSRESPONSE._serialized_start=251
  _QUERYPARAMSRESPONSE._serialized_end=335
  _QUERYINFLATIONREQUEST._serialized_start=337
  _QUERYINFLATIONREQUEST._serialized_end=360
  _QUERYINFLATIONRESPONSE._serialized_start=362
  _QUERYINFLATIONRESPONSE._serialized_end=453
  _QUERYSTATEREQUEST._serialized_start=455
  _QUERYSTATEREQUEST._serialized_end=474
  _QUERYSTATERESPONSE._serialized_start=477
  _QUERYSTATERESPONSE._serialized_end=640
  _QUERY._serialized_start=643
  _QUERY._serialized_end=1120
# @@protoc_insertion_point(module_scope)
