# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/transfer/v1/token.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ibc.applications.transfer.v1 import transfer_pb2 as ibc_dot_applications_dot_transfer_dot_v1_dot_transfer__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(ibc/applications/transfer/v1/token.proto\x12\x1cibc.applications.transfer.v1\x1a+ibc/applications/transfer/v1/transfer.proto\x1a\x14gogoproto/gogo.proto\"Q\n\x05Token\x12\x38\n\x05\x64\x65nom\x18\x01 \x01(\x0b\x32#.ibc.applications.transfer.v1.DenomB\x04\xc8\xde\x1f\x00\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\"M\n\x05\x44\x65nom\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\t\x12\x36\n\x05trace\x18\x03 \x03(\x0b\x32!.ibc.applications.transfer.v1.HopB\x04\xc8\xde\x1f\x00\"0\n\x03Hop\x12\x0f\n\x07port_id\x18\x01 \x01(\t\x12\x12\n\nchannel_id\x18\x02 \x01(\t:\x04\x98\xa0\x1f\x00\x42:Z8github.com/cosmos/ibc-go/v10/modules/apps/transfer/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.applications.transfer.v1.token_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8github.com/cosmos/ibc-go/v10/modules/apps/transfer/types'
  _TOKEN.fields_by_name['denom']._options = None
  _TOKEN.fields_by_name['denom']._serialized_options = b'\310\336\037\000'
  _DENOM.fields_by_name['trace']._options = None
  _DENOM.fields_by_name['trace']._serialized_options = b'\310\336\037\000'
  _HOP._options = None
  _HOP._serialized_options = b'\230\240\037\000'
  _TOKEN._serialized_start=141
  _TOKEN._serialized_end=222
  _DENOM._serialized_start=224
  _DENOM._serialized_end=301
  _HOP._serialized_start=303
  _HOP._serialized_end=351
# @@protoc_insertion_point(module_scope)
