# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/channel/v2/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ibc/core/channel/v2/genesis.proto\x12\x13ibc.core.channel.v2\x1a\x14gogoproto/gogo.proto\"\xc9\x02\n\x0cGenesisState\x12@\n\x10\x61\x63knowledgements\x18\x02 \x03(\x0b\x32 .ibc.core.channel.v2.PacketStateB\x04\xc8\xde\x1f\x00\x12;\n\x0b\x63ommitments\x18\x03 \x03(\x0b\x32 .ibc.core.channel.v2.PacketStateB\x04\xc8\xde\x1f\x00\x12\x38\n\x08receipts\x18\x04 \x03(\x0b\x32 .ibc.core.channel.v2.PacketStateB\x04\xc8\xde\x1f\x00\x12=\n\rasync_packets\x18\x05 \x03(\x0b\x32 .ibc.core.channel.v2.PacketStateB\x04\xc8\xde\x1f\x00\x12\x41\n\x0esend_sequences\x18\x06 \x03(\x0b\x32#.ibc.core.channel.v2.PacketSequenceB\x04\xc8\xde\x1f\x00\"F\n\x0bPacketState\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c:\x04\x88\xa0\x1f\x00\"5\n\x0ePacketSequence\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\x04\x42?Z=github.com/cosmos/ibc-go/v10/modules/core/04-channel/v2/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.core.channel.v2.genesis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z=github.com/cosmos/ibc-go/v10/modules/core/04-channel/v2/types'
  _GENESISSTATE.fields_by_name['acknowledgements']._options = None
  _GENESISSTATE.fields_by_name['acknowledgements']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['commitments']._options = None
  _GENESISSTATE.fields_by_name['commitments']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['receipts']._options = None
  _GENESISSTATE.fields_by_name['receipts']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['async_packets']._options = None
  _GENESISSTATE.fields_by_name['async_packets']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE.fields_by_name['send_sequences']._options = None
  _GENESISSTATE.fields_by_name['send_sequences']._serialized_options = b'\310\336\037\000'
  _PACKETSTATE._options = None
  _PACKETSTATE._serialized_options = b'\210\240\037\000'
  _GENESISSTATE._serialized_start=81
  _GENESISSTATE._serialized_end=410
  _PACKETSTATE._serialized_start=412
  _PACKETSTATE._serialized_end=482
  _PACKETSEQUENCE._serialized_start=484
  _PACKETSEQUENCE._serialized_end=537
# @@protoc_insertion_point(module_scope)
