# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/lightclients/wasm/v1/wasm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from ibc.core.client.v1 import client_pb2 as ibc_dot_core_dot_client_dot_v1_dot_client__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ibc/lightclients/wasm/v1/wasm.proto\x12\x18ibc.lightclients.wasm.v1\x1a\x14gogoproto/gogo.proto\x1a\x1fibc/core/client/v1/client.proto\"l\n\x0b\x43lientState\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08\x63hecksum\x18\x02 \x01(\x0c\x12\x37\n\rlatest_height\x18\x03 \x01(\x0b\x32\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00:\x04\x88\xa0\x1f\x00\"$\n\x0e\x43onsensusState\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c:\x04\x88\xa0\x1f\x00\"#\n\rClientMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c:\x04\x88\xa0\x1f\x00\"\"\n\tChecksums\x12\x11\n\tchecksums\x18\x01 \x03(\x0c:\x02\x18\x01\x42\x42Z@github.com/cosmos/ibc-go/modules/light-clients/08-wasm/v10/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.lightclients.wasm.v1.wasm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z@github.com/cosmos/ibc-go/modules/light-clients/08-wasm/v10/types'
  _CLIENTSTATE.fields_by_name['latest_height']._options = None
  _CLIENTSTATE.fields_by_name['latest_height']._serialized_options = b'\310\336\037\000'
  _CLIENTSTATE._options = None
  _CLIENTSTATE._serialized_options = b'\210\240\037\000'
  _CONSENSUSSTATE._options = None
  _CONSENSUSSTATE._serialized_options = b'\210\240\037\000'
  _CLIENTMESSAGE._options = None
  _CLIENTMESSAGE._serialized_options = b'\210\240\037\000'
  _CHECKSUMS._options = None
  _CHECKSUMS._serialized_options = b'\030\001'
  _CLIENTSTATE._serialized_start=120
  _CLIENTSTATE._serialized_end=228
  _CONSENSUSSTATE._serialized_start=230
  _CONSENSUSSTATE._serialized_end=266
  _CLIENTMESSAGE._serialized_start=268
  _CLIENTMESSAGE._serialized_end=303
  _CHECKSUMS._serialized_start=305
  _CHECKSUMS._serialized_end=339
# @@protoc_insertion_point(module_scope)
