# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ibc.core.client.v2 import tx_pb2 as ibc_dot_core_dot_client_dot_v2_dot_tx__pb2


class MsgStub(object):
    """Msg defines the ibc/client/v2 Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterCounterparty = channel.unary_unary(
                '/ibc.core.client.v2.Msg/RegisterCounterparty',
                request_serializer=ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgRegisterCounterparty.SerializeToString,
                response_deserializer=ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgRegisterCounterpartyResponse.FromString,
                )
        self.UpdateClientConfig = channel.unary_unary(
                '/ibc.core.client.v2.Msg/UpdateClientConfig',
                request_serializer=ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgUpdateClientConfig.SerializeToString,
                response_deserializer=ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgUpdateClientConfigResponse.FromString,
                )


class MsgServicer(object):
    """Msg defines the ibc/client/v2 Msg service.
    """

    def RegisterCounterparty(self, request, context):
        """RegisterCounterparty defines a rpc handler method for MsgRegisterCounterparty.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClientConfig(self, request, context):
        """UpdateClientConfig defines a rpc handler method for MsgUpdateClientConfig.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterCounterparty': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCounterparty,
                    request_deserializer=ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgRegisterCounterparty.FromString,
                    response_serializer=ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgRegisterCounterpartyResponse.SerializeToString,
            ),
            'UpdateClientConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClientConfig,
                    request_deserializer=ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgUpdateClientConfig.FromString,
                    response_serializer=ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgUpdateClientConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ibc.core.client.v2.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the ibc/client/v2 Msg service.
    """

    @staticmethod
    def RegisterCounterparty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ibc.core.client.v2.Msg/RegisterCounterparty',
            ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgRegisterCounterparty.SerializeToString,
            ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgRegisterCounterpartyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateClientConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ibc.core.client.v2.Msg/UpdateClientConfig',
            ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgUpdateClientConfig.SerializeToString,
            ibc_dot_core_dot_client_dot_v2_dot_tx__pb2.MsgUpdateClientConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
