# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/client/v2/tx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from ibc.core.client.v2 import config_pb2 as ibc_dot_core_dot_client_dot_v2_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bibc/core/client/v2/tx.proto\x12\x12ibc.core.client.v2\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\x1a\x1fibc/core/client/v2/config.proto\"\x91\x01\n\x17MsgRegisterCounterparty\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\"\n\x1a\x63ounterparty_merkle_prefix\x18\x02 \x03(\x0c\x12\x1e\n\x16\x63ounterparty_client_id\x18\x03 \x01(\t\x12\x0e\n\x06signer\x18\x04 \x01(\t:\x0f\x82\xe7\xb0*\x06signer\x88\xa0\x1f\x00\"!\n\x1fMsgRegisterCounterpartyResponse\"}\n\x15MsgUpdateClientConfig\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x30\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x1a.ibc.core.client.v2.ConfigB\x04\xc8\xde\x1f\x00\x12\x0e\n\x06signer\x18\x03 \x01(\t:\x0f\x82\xe7\xb0*\x06signer\x88\xa0\x1f\x00\"\x1f\n\x1dMsgUpdateClientConfigResponse2\xfa\x01\n\x03Msg\x12x\n\x14RegisterCounterparty\x12+.ibc.core.client.v2.MsgRegisterCounterparty\x1a\x33.ibc.core.client.v2.MsgRegisterCounterpartyResponse\x12r\n\x12UpdateClientConfig\x12).ibc.core.client.v2.MsgUpdateClientConfig\x1a\x31.ibc.core.client.v2.MsgUpdateClientConfigResponse\x1a\x05\x80\xe7\xb0*\x01\x42>Z<github.com/cosmos/ibc-go/v10/modules/core/02-client/v2/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.core.client.v2.tx_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z<github.com/cosmos/ibc-go/v10/modules/core/02-client/v2/types'
  _MSGREGISTERCOUNTERPARTY._options = None
  _MSGREGISTERCOUNTERPARTY._serialized_options = b'\202\347\260*\006signer\210\240\037\000'
  _MSGUPDATECLIENTCONFIG.fields_by_name['config']._options = None
  _MSGUPDATECLIENTCONFIG.fields_by_name['config']._serialized_options = b'\310\336\037\000'
  _MSGUPDATECLIENTCONFIG._options = None
  _MSGUPDATECLIENTCONFIG._serialized_options = b'\202\347\260*\006signer\210\240\037\000'
  _MSG._options = None
  _MSG._serialized_options = b'\200\347\260*\001'
  _MSGREGISTERCOUNTERPARTY._serialized_start=132
  _MSGREGISTERCOUNTERPARTY._serialized_end=277
  _MSGREGISTERCOUNTERPARTYRESPONSE._serialized_start=279
  _MSGREGISTERCOUNTERPARTYRESPONSE._serialized_end=312
  _MSGUPDATECLIENTCONFIG._serialized_start=314
  _MSGUPDATECLIENTCONFIG._serialized_end=439
  _MSGUPDATECLIENTCONFIGRESPONSE._serialized_start=441
  _MSGUPDATECLIENTCONFIGRESPONSE._serialized_end=472
  _MSG._serialized_start=475
  _MSG._serialized_end=725
# @@protoc_insertion_point(module_scope)
