# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c4echain/cfesignature/signature.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%c4echain/cfesignature/signature.proto\x12\"chain4energy.c4echain.cfesignature\x1a\x14gogoproto/gogo.proto\"Y\n\tSignature\x12\x11\n\tsignature\x18\x01 \x01(\t\x12\x11\n\talgorithm\x18\x02 \x01(\t\x12\x13\n\x0b\x63\x65rtificate\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\tB8Z6github.com/chain4energy/c4e-chain/x/cfesignature/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c4echain.cfesignature.signature_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6github.com/chain4energy/c4e-chain/x/cfesignature/types'
  _SIGNATURE._serialized_start=99
  _SIGNATURE._serialized_end=188
# @@protoc_insertion_point(module_scope)
