# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c4echain/cfeminter/params.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from c4echain.cfeminter import minter_pb2 as c4echain_dot_cfeminter_dot_minter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63\x34\x65\x63hain/cfeminter/params.proto\x12\x1f\x63hain4energy.c4echain.cfeminter\x1a\x14gogoproto/gogo.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1f\x63\x34\x65\x63hain/cfeminter/minter.proto\"\x96\x01\n\x06Params\x12\x12\n\nmint_denom\x18\x01 \x01(\t\x12\x38\n\nstart_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\xc8\xde\x1f\x00\x90\xdf\x1f\x01\x12\x38\n\x07minters\x18\x03 \x03(\x0b\x32\'.chain4energy.c4echain.cfeminter.Minter:\x04\x98\xa0\x1f\x00\x42\x35Z3github.com/chain4energy/c4e-chain/x/cfeminter/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c4echain.cfeminter.params_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/chain4energy/c4e-chain/x/cfeminter/types'
  _PARAMS.fields_by_name['start_time']._options = None
  _PARAMS.fields_by_name['start_time']._serialized_options = b'\310\336\037\000\220\337\037\001'
  _PARAMS._options = None
  _PARAMS._serialized_options = b'\230\240\037\000'
  _PARAMS._serialized_start=157
  _PARAMS._serialized_end=307
# @@protoc_insertion_point(module_scope)
