# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/airdrop/v1beta1/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.airdrop.v1beta1 import airdrop_pb2 as cosmos_dot_airdrop_dot_v1beta1_dot_airdrop__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63osmos/airdrop/v1beta1/tx.proto\x12\x16\x63osmos.airdrop.v1beta1\x1a\x14gogoproto/gogo.proto\x1a$cosmos/airdrop/v1beta1/airdrop.proto\"\x82\x01\n\nMsgAirDrop\x12-\n\x0c\x66rom_address\x18\x01 \x01(\tB\x17\xf2\xde\x1f\x13yaml:\"from_address\"\x12;\n\x04\x66und\x18\x02 \x01(\x0b\x32\x1c.cosmos.airdrop.v1beta1.FundB\x0f\xf2\xde\x1f\x0byaml:\"fund\":\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00\"\x14\n\x12MsgAirDropResponse2`\n\x03Msg\x12Y\n\x07\x41irDrop\x12\".cosmos.airdrop.v1beta1.MsgAirDrop\x1a*.cosmos.airdrop.v1beta1.MsgAirDropResponseB.Z,github.com/cosmos/cosmos-sdk/x/airdrop/typesb\x06proto3')



_MSGAIRDROP = DESCRIPTOR.message_types_by_name['MsgAirDrop']
_MSGAIRDROPRESPONSE = DESCRIPTOR.message_types_by_name['MsgAirDropResponse']
MsgAirDrop = _reflection.GeneratedProtocolMessageType('MsgAirDrop', (_message.Message,), {
  'DESCRIPTOR' : _MSGAIRDROP,
  '__module__' : 'cosmos.airdrop.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.airdrop.v1beta1.MsgAirDrop)
  })
_sym_db.RegisterMessage(MsgAirDrop)

MsgAirDropResponse = _reflection.GeneratedProtocolMessageType('MsgAirDropResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGAIRDROPRESPONSE,
  '__module__' : 'cosmos.airdrop.v1beta1.tx_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.airdrop.v1beta1.MsgAirDropResponse)
  })
_sym_db.RegisterMessage(MsgAirDropResponse)

_MSG = DESCRIPTOR.services_by_name['Msg']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z,github.com/cosmos/cosmos-sdk/x/airdrop/types'
  _MSGAIRDROP.fields_by_name['from_address']._options = None
  _MSGAIRDROP.fields_by_name['from_address']._serialized_options = b'\362\336\037\023yaml:\"from_address\"'
  _MSGAIRDROP.fields_by_name['fund']._options = None
  _MSGAIRDROP.fields_by_name['fund']._serialized_options = b'\362\336\037\013yaml:\"fund\"'
  _MSGAIRDROP._options = None
  _MSGAIRDROP._serialized_options = b'\350\240\037\000\210\240\037\000'
  _MSGAIRDROP._serialized_start=120
  _MSGAIRDROP._serialized_end=250
  _MSGAIRDROPRESPONSE._serialized_start=252
  _MSGAIRDROPRESPONSE._serialized_end=272
  _MSG._serialized_start=274
  _MSG._serialized_end=370
# @@protoc_insertion_point(module_scope)
