# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from cosmos.counter.v1 import tx_pb2 as cosmos_dot_counter_dot_v1_dot_tx__pb2


class MsgStub(object):
    """Msg defines the counter Msg service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IncreaseCount = channel.unary_unary(
                '/cosmos.counter.v1.Msg/IncreaseCount',
                request_serializer=cosmos_dot_counter_dot_v1_dot_tx__pb2.MsgIncreaseCounter.SerializeToString,
                response_deserializer=cosmos_dot_counter_dot_v1_dot_tx__pb2.MsgIncreaseCountResponse.FromString,
                )


class MsgServicer(object):
    """Msg defines the counter Msg service.
    """

    def IncreaseCount(self, request, context):
        """IncreaseCount increments the counter by the specified amount.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IncreaseCount': grpc.unary_unary_rpc_method_handler(
                    servicer.IncreaseCount,
                    request_deserializer=cosmos_dot_counter_dot_v1_dot_tx__pb2.MsgIncreaseCounter.FromString,
                    response_serializer=cosmos_dot_counter_dot_v1_dot_tx__pb2.MsgIncreaseCountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cosmos.counter.v1.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Msg defines the counter Msg service.
    """

    @staticmethod
    def IncreaseCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cosmos.counter.v1.Msg/IncreaseCount',
            cosmos_dot_counter_dot_v1_dot_tx__pb2.MsgIncreaseCounter.SerializeToString,
            cosmos_dot_counter_dot_v1_dot_tx__pb2.MsgIncreaseCountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
