# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/interchain_accounts/host/v1/tx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from ibc.applications.interchain_accounts.host.v1 import host_pb2 as ibc_dot_applications_dot_interchain__accounts_dot_host_dot_v1_dot_host__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5ibc/applications/interchain_accounts/host/v1/tx.proto\x12,ibc.applications.interchain_accounts.host.v1\x1a\x14gogoproto/gogo.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x37ibc/applications/interchain_accounts/host/v1/host.proto\"~\n\x0fMsgUpdateParams\x12\x0e\n\x06signer\x18\x01 \x01(\t\x12J\n\x06params\x18\x02 \x01(\x0b\x32\x34.ibc.applications.interchain_accounts.host.v1.ParamsB\x04\xc8\xde\x1f\x00:\x0f\x82\xe7\xb0*\x06signer\x88\xa0\x1f\x00\"\x19\n\x17MsgUpdateParamsResponse\"\x89\x01\n\x12MsgModuleQuerySafe\x12\x0e\n\x06signer\x18\x01 \x01(\t\x12R\n\x08requests\x18\x02 \x03(\x0b\x32:.ibc.applications.interchain_accounts.host.v1.QueryRequestB\x04\xc8\xde\x1f\x00:\x0f\x82\xe7\xb0*\x06signer\x88\xa0\x1f\x00\"?\n\x1aMsgModuleQuerySafeResponse\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x11\n\tresponses\x18\x02 \x03(\x0c\x32\xc3\x02\n\x03Msg\x12\x94\x01\n\x0cUpdateParams\x12=.ibc.applications.interchain_accounts.host.v1.MsgUpdateParams\x1a\x45.ibc.applications.interchain_accounts.host.v1.MsgUpdateParamsResponse\x12\x9d\x01\n\x0fModuleQuerySafe\x12@.ibc.applications.interchain_accounts.host.v1.MsgModuleQuerySafe\x1aH.ibc.applications.interchain_accounts.host.v1.MsgModuleQuerySafeResponse\x1a\x05\x80\xe7\xb0*\x01\x42MZKgithub.com/cosmos/ibc-go/v10/modules/apps/27-interchain-accounts/host/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.applications.interchain_accounts.host.v1.tx_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZKgithub.com/cosmos/ibc-go/v10/modules/apps/27-interchain-accounts/host/types'
  _MSGUPDATEPARAMS.fields_by_name['params']._options = None
  _MSGUPDATEPARAMS.fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _MSGUPDATEPARAMS._options = None
  _MSGUPDATEPARAMS._serialized_options = b'\202\347\260*\006signer\210\240\037\000'
  _MSGMODULEQUERYSAFE.fields_by_name['requests']._options = None
  _MSGMODULEQUERYSAFE.fields_by_name['requests']._serialized_options = b'\310\336\037\000'
  _MSGMODULEQUERYSAFE._options = None
  _MSGMODULEQUERYSAFE._serialized_options = b'\202\347\260*\006signer\210\240\037\000'
  _MSG._options = None
  _MSG._serialized_options = b'\200\347\260*\001'
  _MSGUPDATEPARAMS._serialized_start=207
  _MSGUPDATEPARAMS._serialized_end=333
  _MSGUPDATEPARAMSRESPONSE._serialized_start=335
  _MSGUPDATEPARAMSRESPONSE._serialized_end=360
  _MSGMODULEQUERYSAFE._serialized_start=363
  _MSGMODULEQUERYSAFE._serialized_end=500
  _MSGMODULEQUERYSAFERESPONSE._serialized_start=502
  _MSGMODULEQUERYSAFERESPONSE._serialized_end=565
  _MSG._serialized_start=568
  _MSG._serialized_end=891
# @@protoc_insertion_point(module_scope)
